spring:
  application:
    name: tracego-server

  datasource:
    url: jdbc:mysql://localhost:3306/tracego_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: master
    password: 20250710
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: info

spring.devtools:
  restart.enabled: true
  livereload.enabled: true

spring.web:
  encoding.charset: UTF-8